<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIaPMHA3\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIaPMHA3/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIaPMHA3.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIaPMHA3\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIaPMHA3\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IaPMHA3',
    'container.build_id' => '4535a890',
    'container.build_time' => 1541846162,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIaPMHA3');
